src/VenueManagement/VM.Web/Controllers/BasketController.cs
using AutoMapper;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using VM.DataAccess.Entities;
using VM.Extensions;
using VM.Services.Contracts;
using VM.Services.DTO;
using VM.Web.App_LocalResources;
using VM.Web.Infrastructure.Mailing.Interfaces;
using VM.Web.Models.Basket;

namespace VM.Web.Controllers
{
    public class BasketController : BaseController
    {
        private readonly IBasketServiceContract _basketService;
        private readonly IOrderServiceContract _orderService;
        private readonly IMailClient _mailClient;
        private readonly IMapper _mapper;

        private BasketModel GetBasketModel()
        {
            var seats = _mapper.Map<IEnumerable<BasketItemDTO>, IEnumerable<BasketItem>>(_basketService.GetCurrentBasketItems(UserId)).ToList();
            var summary = _basketService.GetBasketSummaryPrice(UserId);
            var user = UserManager.FindByName(UserName);

            var model = new BasketModel
            {
                Balance = user.Balance,
                BalanceLabel = user.Balance.ToPriceString(GetUserCulture()),
                Summary = summary,
                SummaryLabel = summary.ToPriceString(GetUserCulture()),
                Seats = seats
            };

            if(seats.Any())
            {
                model.BasketExpiryDate = seats.First().ExpiryDate;
            }

            return model;
        }

        public BasketController(IBasketServiceContract basketService, 
            IOrderServiceContract orderService,
            IMailClient mailClient,
            IMapper mapper)
        {
            _basketService = basketService;
            _orderService = orderService;
            _mailClient = mailClient;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            _basketService.ClearExpiredBasketItems(UserId);
            var basketModel = GetBasketModel();

            return View(basketModel);
        }

        [HttpPost]
        public ActionResult ConfirmBasket()
        {
            var currentBasketItems = _mapper.Map<IEnumerable<BasketItemDTO>, IEnumerable<BasketItem>>(_basketService.GetCurrentBasketItems(UserId)).ToList();
            if (!currentBasketItems.Any())
            {
                var basketModel = GetBasketModel();
                ModelState.AddModelError("BasketExpired", Resources.BasketItemsExpiredErrorMessage);
                return View("Index", basketModel);
            }

            var user = UserManager.FindByName(UserName);
            var summary = _basketService.GetBasketSummaryPrice(UserId);

            _orderService.CreateOrderByUserIdAndPrice(UserId, summary);
            _mailClient.SendConfirmation(user, currentBasketItems, summary);
            _basketService.ClearBasketItems(UserId);

            return RedirectToAction(actionName: "", controllerName: "");
        }

        [HttpPost]
        public ActionResult RemoveFromBasket(int link)
        {
            _basketService.DeleteBasketItemById(link);
            _basketService.UpdateBasketItemExpiry(UserId);

            return RedirectToAction("Index");
        }
    }
}

src/VenueManagement/VM.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Venue Management</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.deep_purple-indigo.min.css" />
        <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
        @Styles.Render("~/Content/css")
    </head>
    <body class="mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
        <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

            <div class="android-header mdl-layout__header mdl-layout__header--waterfall">
                <div class="mdl-layout__header-row">
                    <div class="android-header-spacer mdl-layout-spacer"></div>
                    <div class="android-navigation-container">
                        <nav class="android-navigation mdl-navigation">
                            @Html.ActionLink(Resources.HomeLabel, "Index", "Home", null, new { @class = "mdl-navigation__link mdl-typography--text-uppercase", id = "headerbutton-home" })
                            @Html.ActionLink(Resources.EventsLabel, "Events", "Event", null, new { @class = "mdl-navigation__link mdl-typography--text-uppercase", id = "headerbutton-events" })
                            @if (Request.IsAuthenticated)
                            {
                                @Html.ActionLink(Resources.BasketLabel, "Index", "Basket", null, new { @class = "mdl-navigation__link mdl-typography--text-uppercase", id = "headerbutton-basket" })
                            }
                            else
                            {
                                @Html.ActionLink(Resources.RegisterLabel, "Register", "Account", null, new { @class = "mdl-navigation__link mdl-typography--text-uppercase", id = "headerbutton-register" })
                                @Html.ActionLink(Resources.LoginLabel, "Login", "Account", null, new { @class = "mdl-navigation__link mdl-typography--text-uppercase", id = "headerbutton-login" })
                            }
                        </nav>
                    </div>

                    @if (Request.IsAuthenticated)
                    {
                        <button class="android-more-button mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="more-button">
                            <i class="material-icons">more_vert</i>
                        </button>
                        <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect mdl-js-ripple-effect--ignore-events" for="more-button">
                            <li class="mdl-menu__item sub-menu-item">@Html.ActionLink(Resources.AccountLabel, "UpdateAccount", "Account", null, new { @class = "mdl-navigation__link sub-menu mdl-typography--text-uppercase", id = "headerbutton-account" })</li>
                            <li class="mdl-menu__item sub-menu-item">@Html.ActionLink(Resources.HistoryLabel, "History", "Account", null, new { @class = "mdl-navigation__link sub-menu mdl-typography--text-uppercase", id = "headerbutton-history" })</li>
                            <li class="mdl-menu__item sub-menu-item">@Html.ActionLink(Resources.LogoutLabel, "Logoff", "Account", null, new { @class = "mdl-navigation__link sub-menu mdl-typography--text-uppercase", id = "headerbutton-logoff" })</li>
                        </ul>
                    }

                </div>
            </div>
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                <div class="android-drawer mdl-layout__drawer">
                    <nav class="mdl-navigation">
                        <div class="android-drawer-separator"></div>
                        <span class="mdl-navigation__link drawer-header">
                            <text class="drawer-header-text">Event Management</text>
                        </span>
                        <div class="android-drawer-separator"></div>
                        @Html.ActionLink(Resources.CreateNewEventLabel, "Create", "Event", null, new { @class = "mdl-navigation__link", id = "drawer-createevent" })
                    </nav>
                </div>
            }
            <div class="body-container">
                @RenderBody()
            </div>
            <div class="android-content mdl-layout__content">
                <footer class="android-footer mdl-mega-footer">
                    <div class="mdl-mega-footer--middle-section">
                        <p class="mdl-typography--font-light">Venue Management © 2020</p>
                        <p class="mdl-typography--font-light">@Resources.FooterWarning</p>
                    </div>
                </footer>
            </div>
        </div>
    </body>
    @RenderSection("scripts", required: false)
</html>